# Generated by Django 6.0.2 on 2026-02-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0005_alter_dish_description'),
    ]

    operations = [
    ]
