# Generated by Django 6.0.2 on 2026-02-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_create_default_category'),
        ('kitchen', '0006_create_default_category'),
    ]

    operations = [
    ]
